package com.example.sms.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

/**
 * Represents a Grade entity in the Student Management System.
 * This entity stores information about a student's grade in a particular subject.
 *
 * Uses Lombok annotations to reduce boilerplate code for getters, setters,
 * constructors, equals, hashCode, and toString methods.
 */
@Entity // Marks this class as a JPA entity, mapping it to a database table.
@Table(name = "grades") // Specifies the name of the database table for this entity.
@Getter // Generates all the getter methods for the fields.
@Setter // Generates all the setter methods for the fields.
@NoArgsConstructor // Generates a no-argument constructor.
@AllArgsConstructor // Generates a constructor with all fields as arguments.
@EqualsAndHashCode(exclude = "student") // Generates equals and hashCode methods, excluding the 'student' field
                                       // to prevent potential infinite loops in bidirectional relationships
                                       // and ensure proper equality checks based on Grade's own attributes.
@ToString(exclude = "student") // Generates a toString method, excluding the 'student' field for the same reasons
                               // as EqualsAndHashCode.
public class Grade {

    /**
     * Unique identifier for the grade.
     * This will be the primary key in the 'grades' table.
     */
    @Id // Marks this field as the primary key.
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the primary key to be auto-generated by the database.
    private Long id;

    /**
     * The student to whom this grade belongs.
     * Establishes a Many-to-One relationship with the Student entity.
     * Multiple grades can belong to one student.
     */
    @ManyToOne(fetch = FetchType.LAZY) // Many grades to one student. FetchType.LAZY means the student will be loaded
                                       // only when explicitly accessed, improving performance.
    @JoinColumn(name = "student_id", nullable = false) // Specifies the foreign key column in the 'grades' table
                                                       // that references the 'students' table. It cannot be null.
    private Student student;

    /**
     * The subject for which the grade was given (e.g., "Mathematics", "Physics").
     */
    @Column(nullable = false) // This column cannot be null in the database.
    private String subject;

    /**
     * The numerical score obtained by the student for this subject.
     */
    @Column(nullable = false) // This column cannot be null in the database.
    private Double score;

    /**
     * The date when the grade was recorded.
     */
    @Column(name = "grade_date", nullable = false) // Specifies the column name in the database and ensures it's not null.
    private LocalDate gradeDate;

    /**
     * Optional notes or comments about the grade.
     */
    @Column(length = 500) // Sets a maximum length for the notes column.
    private String notes;

    // Custom constructor for convenience, excluding ID which is auto-generated.
    public Grade(Student student, String subject, Double score, LocalDate gradeDate, String notes) {
        this.student = student;
        this.subject = subject;
        this.score = score;
        this.gradeDate = gradeDate;
        this.notes = notes;
    }
}